

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_24 = Integer(24); _sage_const_22 = Integer(22); _sage_const_20 = Integer(20); _sage_const_14 = Integer(14); _sage_const_8 = Integer(8); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_18 = Integer(18); _sage_const_16 = Integer(16); _sage_const_12 = Integer(12); _sage_const_10 = Integer(10); _sage_const_26 = Integer(26); _sage_const_30 = Integer(30); _sage_const_28 = Integer(28); _sage_const_36 = Integer(36); _sage_const_34 = Integer(34); _sage_const_32 = Integer(32); _sage_const_0 = Integer(0)
R = RealField(_sage_const_100 )

a = R(e) ** (R(pi) * i / R(_sage_const_5 ))
b = a**_sage_const_2 

coefs = [_sage_const_1 /(a**_sage_const_24  - a**_sage_const_22  - a**_sage_const_20  + _sage_const_2 *a**_sage_const_14  - a**_sage_const_8  - a**_sage_const_6  + a**_sage_const_4 ), _sage_const_1 /(-a**_sage_const_24  + _sage_const_2 *a**_sage_const_22  - a**_sage_const_18  - a**_sage_const_16  + _sage_const_2 *a**_sage_const_12  - a**_sage_const_10 ), (-_sage_const_1 )/(-a**_sage_const_26  + _sage_const_2 *a**_sage_const_24  + a**_sage_const_22  - _sage_const_4 *a**_sage_const_20  + a**_sage_const_18  + _sage_const_2 *a**_sage_const_16  - a**_sage_const_14 ), _sage_const_1 /(-a**_sage_const_30  + _sage_const_2 *a**_sage_const_28  - a**_sage_const_24  - a**_sage_const_22  + _sage_const_2 *a**_sage_const_18  - a**_sage_const_16 ), (-_sage_const_1 )/(-a**_sage_const_36  + a**_sage_const_34  + a**_sage_const_32  - _sage_const_2 *a**_sage_const_26  + a**_sage_const_20  + a**_sage_const_18  - a**_sage_const_16 )]

A, B = _sage_const_0 , _sage_const_1 

ans = _sage_const_0 

for i in range(_sage_const_5 ):
	ans += coefs[i] * (ln(B - a * b**i) - ln(A - a * b**i))

print(ans)

